"""is_active field added

Revision ID: f8d06d65c607
Revises: 2b4284c5a93f
Create Date: 2024-10-31 00:56:37.652841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d06d65c607'
down_revision: Union[str, None] = '2b4284c5a93f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('two_factor_auth', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('two_factor_auth', 'is_active')
    # ### end Alembic commands ###
